# .github/dependabot.yml
version: 2
updates:
  # GitHub Actions の自動更新
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - kotaoue

  # npm パッケージの自動更新
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - kotaoue